[package]
name = "aci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
urlencoding = "1.0.0"
itertools = "0.10.2"
